In [2]:
from sklearn import tree
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
df_tr = pd.read_csv(r'https://stepik.org/media/attachments/course/4852/dogs_n_cats.csv')

In [25]:
X = df_tr.drop(['Вид'], axis=1)
y = df_tr['Вид']

In [8]:
X_train, X_test, y_train, y_test =  train_test_split(X,y,test_size=0.33,random_state=42)
clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [33]:
df_ts = pd.read_json(r'C:\Users\Artem\Downloads\dataset_209691_15.txt')

In [24]:
df_tr

     Длина  Высота  Шерстист  Гавкает  Лазает по деревьям      Вид
0       15    18.0         1        1                   0  собачка
1       20    24.0         1        0                   0  собачка
2       34    40.8         1        1                   0  собачка
3       26    31.2         1        1                   0  собачка
4       16    19.2         1        1                   0  собачка
..     ...     ...       ...      ...                 ...      ...
995      8     3.2         1        0                   1    котик
996      7     2.8         1        0                   1    котик
997      6     2.4         1        0                   1    котик
998      7     2.8         1        0                   1    котик
999     11     4.4         1        0                   1    котик

[1000 rows x 6 columns]

In [21]:
df_ts

    Длина  Высота  Шерстист  Гавкает  Лазает по деревьям
0      20    24.0         1        1                   0
1      33    39.6         1        1                   0
2      20    24.0         1        1                   0
3      15    18.0         1        0                   0
4      23    27.6         1        1                   0
..    ...     ...       ...      ...                 ...
95      7     2.8         1        0                   1
96      8     3.2         1        0                   1
97      5     2.0         1        0                   1
98     13     5.2         1        0                   1
99      8     3.2         1        0                   1

[100 rows x 5 columns]

In [23]:
df_ts[:2]
df_tr[:2]

   Длина  Высота  Шерстист  Гавкает  Лазает по деревьям      Вид
0     15    18.0         1        1                   0  собачка
1     20    24.0         1        0                   0  собачка

In [34]:
result = clf.predict(df_ts)
pd.Series(result)[result == 'собачка'].count()

40